#!/bin/bash

# For druid ansible stuffz:
export TF_VAR_region="us-east-1"
export TF_VAR_environment="development"

export TF_VAR_aws_access_key_id=$AWS_ACCESS_KEY
export TF_VAR_aws_secret_access_key=$AWS_SECRET_ACCESS_KEY

export TF_VAR_az_one="us-east-1b"
export TF_VAR_az_two="us-east-1c"

export TF_VAR_security_group_id="<SECURITY GROUP>"
export TF_VAR_subnet_one="<SUBNET>"
export TF_VAR_subnet_two="<SUBNET>"
export TF_VAR_vpc_id="<VPC ID>"

export TF_VAR_date=`date +%s`

