#!/bin/bash

# For druid ansible stuffz:
export TF_VAR_region="us-east-1"
export TF_VAR_environment="development"

export TF_VAR_aws_access_key_id=$AWS_ACCESS_KEY
export TF_VAR_aws_secret_access_key=$AWS_SECRET_ACCESS_KEY

export TF_VAR_date=`date +%s`

